[package]
name = "simulador-z80"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
rstest = "0.26.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }